title: "Grande | software store"
email: adammohamud.abdulla@graduate.utm.my
timezone: UTC
url: "https://github.com"
baseurl: "/Grante-site"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Adam
paginate: 30
disqus: 'Grante'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  sal:
    name: Adam
    display_name: Adam
    avatar: 'assets/images/sal.png'
    email: adammohamud.abdulla
    web: https://google.com
    twitter: https://twitter.com
    description: "Student at UTM."
  john:
    name: Ting
    display_name: Ting
    avatar: 'assets/images/john.png'
    email: ting
    web: https://www.google.com
    twitter: https://twitter.com
    description: "UTM student."

# Social
social:
  instagram: https://www.instagram.com
  facebook: https://www.facebook.com
  twitter: https://twitter.com

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives